theme = "catppuccin_mocha"

[editor]
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.smart-tab]
enable = false

[keys.normal]
J = "select_line_below"
K = "select_line_above"

