F     script-binding quality_menu/video_formats_toggle #! Stream Quality > Video
Alt+f script-binding quality_menu/audio_formats_toggle #! Stream Quality > Audio

KP0 run "/home/lenicyl/.config/mpv/sh/vulkanswap.sh" -f "${path}" -t "${=time-pos}" -p "nvidia" -i "${pid}"
