## General ##
keepaspect-window=no                                                # Allow free resizing of the player without deformation of media
keep-open=yes                                                       # Keep mpv open after media ends
msg-module=yes                                                      # Use module names for each console output


## GPU ##
vo=gpu-next                                                         # Select video output driver.    
hwdec=auto-copy-safe                                                # Setting it to Vulkan ends up with problems for me
gpu-api=vulkan                                                      # Controls what graphics api to use. Use auto in case of issues
gpu-context=waylandvk                                               # Set to x11vk if video playback doesnt work
vulkan-device='Intel(R) HD Graphics 530 (SKL GT2)'                  # Select Intel integrated GPU by default 


## Video ##
#profile=gpu-hq                                                      # High quality rendering profile. 
#video-sync=display-resample                                         # Resamples audio to match video


## OSC ##
osc=no
osd-bar=no
border=no


## Screenshots ##
screenshot-format=png
#screenshot-template=%F%wm%n
screenshot-dir="/home/lenicyl/Pictures/mpv/"


## Subtitles ##
sub-scale=0.5
sub-pos=99


[UHD]
profile-cond=width>=3840 or height>=2160


[QHD]


[FHD]


[nvidia]                                                            # use with mpv --profile="nvidia", conditional profiles doesnt work for swapping vulkan devices
vulkan-device='NVIDIA GeForce GTX 960M'			                    # Select Nvidia discrete GPU by default
#hwdec=nvdec                                                         # Uses the nvidia hardware decoder
#gpu-context=x11vk                                                   # Using nvidia in wayland context causes video output to fails 

