#!/bin/sh

brightnessctl set "$1"
current_brightness=$(brightnessctl get)
max_brightness=$(brightnessctl max)
brightness=$(( current_brightness*100/max_brightness ))
notify-send -t 1000 -a 'bright' -h int:value:$brightness "Brightness: ${brightness}%"
