#!/bin/sh

## Verbosity and Overwrite confirm
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'

## Colors
ls=$(command -v eza >/dev/null && echo eza || echo ls)
alias ls='$ls --group-directories-first --color'
alias ll='$ls -la --group-directories-first --color'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
