#!/bin/sh

# ~/.python-history
export PYTHON_HISTORY=$XDG_STATE_HOME/python_history
export PYTHONPYCACHEPREFIX=$XDG_CACHE_HOME/python
export PYTHONUSERBASE=$XDG_DATA_HOME/python

# ~/.inputrc
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc
